query PollGet($id: uuid!) {
  Poll(where: {id: {_eq: $id }}) {
    title
    created_at
    id
    polloptionssBypollId {
      text
      id
      pollvotesBycreatedFor_aggregate {
        aggregate {
          count
        }
      }
    }
  }
}
